### PR TITLE
Isssue #6 fixed

### PR DESCRIPTION
**Pull request by karan2527**
working fine

### CODE REVIEW

**Comment by Aswinr24** [comment]
Deployment is fine but ensure at least the colour scheme is what we are following at the moment, the bg colour should remain the same atleast 
See the achievements and gallery section in this PR for example: https://deploy-preview-12--aegisdsce.netlify.app/
Also try adding something unique to the "About" section

**Review by ifrah-ashraf — COMMENTED** [review]
try to add global.css in the layout.tsx so that easily you can use the global css and the  about us , events , teams pages are working fine .

**Comment by ifrah-ashraf** [comment]
try to add global.css in the layout.tsx so that easily you can use the global css and the about us , events , teams pages are working fine .

**Comment by karan2527** [comment]
> try to add global.css in the layout.tsx so that easily you can use the global css and the about us , events , teams pages are working fine .

done

**Review by sahil-raj — APPROVED** [review]
noice

**Pull request merged**
